### ISSUE TITLE
How to differentiate output based on auth status?

### ISSUE THREAD

**Issue by panta** [alexliesenfeld/health#2]
Commit 739c4a012ae74f2a6b7b2c9efebc7dcee916116a removed `WithCustomAuth` and `WithBasicAuth`.

What's the recommended way to obtain the same behaviour now?

**Comment by alexliesenfeld** [comment]
The idea behind removing it was, because authentication is not a primary concern of a health check library. Because the health check handler is just a standard http.Handler, you can use it in many middleware implementations, such as [this](https://github.com/99designs/basicauth-go) or [this](https://github.com/go-chi/chi/blob/master/middleware/basic_auth.go) .

**Comment by panta** [comment]
Yes, but it's still useful to be able to return a more limited result to non-authenticated clients, instead of returning a 401 or 403. I can implement a middleware calling two different health handlers based on auth status, but in that case I'd have two separate but similar/identical copies of health checkers running in background, no?

**Comment by alexliesenfeld** [comment]
Ah, I understand. Yes, this functionality was removed. However, I see two solutions to this problem:

1. You could create one check Handler but mount it to two different paths using different middleware. This solution is not so nice, though.
2. As a replacement to the removed functionality, I planned to add a more generic function to disable details on a request basis. This way you can decide in which situations you would like to disable details yourself. To do this, you would need to call a `health.DisableResponseDetails(request.Context())` function whenever you want to return the reduced response. This function could be called by your auth middleware. Would this be sufficient for you? This is just a rough sketch.

**Comment by panta** [comment]
The marker/option would be nice. I was also thinking of separating and exposing the checks machinery from the handler(s), thus also allowing to further customize the output and the strategy of handling. I've seen this approach adopted in [hellofresh/health-go](https://github.com/hellofresh/health-go) for example. What would you think?

**Comment by panta** [comment]
I've provided an implementation in [panta/feature/standalone-checkers](https://github.com/panta/health/tree/panta/feature/standalone-checkers) (just a matter of making the `checker` -> `Checker` interface public, add a `NewChecker()` function, and some other very minor adjustments).

If you feel this might be useful to others I'll send a PR.

**Comment by alexliesenfeld** [comment]
Thanks. I looks interesting, indeed! Happy to get a PR for this. I'll look into it tonight.

**Comment by alexliesenfeld** [comment]
Merged with #5

**Comment by alexliesenfeld** [comment]
In case you're still interested in a solution: The new version 0.5.0 has a BasicAuth middleware that should do what you want. I've seen you pulled your star back, probably because of the larger changes that happened recently (based on feedback). This library is stabilizing now - I do not expect larger changes anymore :-).

**Comment by panta** [comment]
Actually I need to use it with a different auth mechanism, but the stand-alone checkers are perfect for that!
Thanks!
