### ISSUE TITLE
Duplicate call to checker Start()?

### ISSUE THREAD

**Issue by panta** [alexliesenfeld/health#4]
Is the call to handler (and thus checker) `Start()` duplicate here:

https://github.com/alexliesenfeld/health/blob/39c698eac61dfe95c78f2535d2f77e669f9ac5e1/config.go#L55-L57

since it's already done from `newChecker()` here?

https://github.com/alexliesenfeld/health/blob/39c698eac61dfe95c78f2535d2f77e669f9ac5e1/check.go#L89-L92

Also I wonder if the `cancel()` deferral doesn't immediately terminate the check here:

https://github.com/alexliesenfeld/health/blob/39c698eac61dfe95c78f2535d2f77e669f9ac5e1/handler.go#L23-L32

**Comment by alexliesenfeld** [comment]
Fixed as part of refactoring in commit 6875c62dfaee5efd7db9d9cbfad07ddb6472e393.

**Comment by alexliesenfeld** [comment]
In case you're still interested in a solution: The new version 0.5.0 has a BasicAuth middleware that should do what you want. I've seen you pulled your star back, probably because of the larger changes that happened recently (based on feedback). This library is stabilizing now - I do not expect larger changes anymore :-).
